// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ9CtSv19WXV47A87PzeUs7rVFs4ufubU',
    appId: '1:640387187266:web:b1cb4d90e8aabfc733a3db',
    messagingSenderId: '640387187266',
    projectId: 'swasthya-camp',
    authDomain: 'swasthya-camp.firebaseapp.com',
    storageBucket: 'swasthya-camp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK4ansIS033vgJEwVEcBvArE01uiwVxfU',
    appId: '1:640387187266:android:688eb456aa1ed13a33a3db',
    messagingSenderId: '640387187266',
    projectId: 'swasthya-camp',
    storageBucket: 'swasthya-camp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0GF6yKWvSXSjdSlqa4UU7zG_5HMJq0tU',
    appId: '1:640387187266:ios:efe33c8fa3ac8efe33a3db',
    messagingSenderId: '640387187266',
    projectId: 'swasthya-camp',
    storageBucket: 'swasthya-camp.appspot.com',
    iosClientId: '640387187266-ol04dfroog0uifgqdr2eoj3t01cfl8pu.apps.googleusercontent.com',
    iosBundleId: 'com.swasthya.swasthyaCamps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0GF6yKWvSXSjdSlqa4UU7zG_5HMJq0tU',
    appId: '1:640387187266:ios:a75d56933c76f93a33a3db',
    messagingSenderId: '640387187266',
    projectId: 'swasthya-camp',
    storageBucket: 'swasthya-camp.appspot.com',
    iosClientId: '640387187266-jia3pcs2lpm1rtdanc1q4khu9fffce07.apps.googleusercontent.com',
    iosBundleId: 'com.swasthya.swasthyaCamps.RunnerTests',
  );
}
